<?php

use \Drupal\user\Entity\User;

function doc_subscription_preprocess_user(&$variables) {
	$authorId = $variables['user']->id();

  $currentUserId = \Drupal::currentUser()->id();
  $currentUser = User::load($currentUserId);
	$subcriptionValues = $currentUser->get('field_subscription')->getValue();

	// on regarde si l'uid existe parmi les références
	$variables['subscription'] = t('Subscribe');

	if (!empty($subcriptionValues)) {
		foreach ($subcriptionValues as $key => $subcriptionValue) {
			if ($authorId == $subcriptionValue['target_id']) {
				$variables['subscription'] = t('Unsubscribe');
				break;
			}
		}
	}

	$variables['authorId'] = $authorId;
	$variables['#attached']['library'][] = 'doc_subscription/subscription';

	$variables['#attached']['drupalSettings']['doc_subscription'] = [
    'authorId' => $authorId,
  ];
}