<?php

function doc_history_preprocess_node(&$variables)
{
  $node = $variables['node'];

  if ($node->getType() == 'doc') {
    $dateFormatter = \Drupal::service('date.formatter');

    $params = [
      'granularity' => 1,
      'return_as_object' => true,
    ];

    $requestTime = \Drupal::time()->getRequestTime();
    $createdAgo = $dateFormatter->formatDiff($node->getCreatedTime(), $requestTime, $params)->getString();
    $variables['createdAgo'] = t('@createdAgo ago', ['@createdAgo' => $createdAgo]);
  }
}

function doc_history_theme($existing, $type, $theme, $path)
{
  $themes = [
    'history' => [
      'variables' => [
        'data' => null,
      ],
    ],
  ];

  return $themes;
}

