default_challenge: captcha/Math
description: 'Cette question permet de déterminer si vous êtes un humain et d''éviter les spams d''enregistrements.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
_core:
  default_config_hash: pfrv6lPS72f5WG1UB4wHkgQV2invlHwVpaCy_mY-ClQ
langcode: fr
