node_title_validation_config:
  comma-doc: 0
  exclude-doc: ''
  min-doc: '3'
  max-doc: '90'
  min-wc-doc: '1'
  max-wc-doc: '25'
  unique-doc: 0
  comma-page: 0
  exclude-page: ''
  min-page: '1'
  max-page: '255'
  min-wc-page: '1'
  max-wc-page: '25'
  unique-page: 0
  unique: 0
